#!/usr/bin/env bash
# executes plays fizzbuzz
for a in {1..100}; do
        fizz=$((a % 3))
        buzz=$((a % 5))
        if [ "$fizz" -eq 0 ] && [ "$buzz" -eq 0 ]; then
                echo "FizzBuzz"
        elif [ "$fizz" -eq 0 ]; then
                echo "Fizz"
        elif [ "$buzz" -eq 0 ]; then
                echo "Buzz"
        else
                echo "$a"
        fi
done
