#!/usr/bin/env bash
# tell the storys
exec 3< "/etc/passwd"

# looping through lines
while IFS=':' read -r username password uid gid info home shell <&3; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done

# closing the file descriptor
exec 3<&-
