#!/usr/bin/env bash
# hour
minutes=1
hour=0

while [ "$hour" -le 12 ]; do
    echo "Hour: $hour"
    minutes=1
    while [ "$minutes" -le 59 ]; do
        echo "$minutes"
        ((minutes++))
    done
    ((hour++))
done
